To do list project
rahalrazika/to-do-list pull request #3
Opened 2021-01-13 12:22 UTC by rahalrazika

A To-do list is an app build with js :

- Built with Webpack
- Created all modules
- for more details please see the readme file.

2021-01-13 13:22 UTC, mikenath223 requested changes
### Hello Team 👋

**You've both done well here. Well structured and modular code 👌**

However, let's make some changes.

- [ ] Currently, it isn't possible to create a new project clicking the `create project` button after filling all form fields returns no action. Kindly check and fix.

- Please refer to other comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2021-01-13 13:23 UTC, mikenath223 commented on src/index.js
> +// document.querySelector('#content').innerHTML = NewItem(project[0]);
- [ ] Please remove these commented code lines. If you want to refer to previous versions of the code consider using git history.

2021-01-15 09:23 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 

Hello, @rahalrazika and @lirad very nice work on this project 👍🏿 . I love the way you have separated your code into modules. 👍🏿  👏🏿 

- [x] When I try to create a to-do, your application throws an error. ⬇️ 
     
![Screenshot from 2021-01-15 12-12-46](https://user-images.githubusercontent.com/32361963/104706075-b6fa4f80-572b-11eb-9704-1903b5fc3c07.png)

The error seems to be in your local storage file. The save project to function. ⬇️  Since as you can see below the local storage is not created. Kindly fix this.

![Screenshot from 2021-01-15 12-13-23](https://user-images.githubusercontent.com/32361963/104706249-e7da8480-572b-11eb-87cc-b560268f203a.png)

Nb: because of the above error your application is not working hence I was not able to review other parts of the application.

- [ ] In your readme file kindly add how to run your project locally.

### if you have any question, kindly reach me on slack @peterrobert

### HAPPY CODING 💻

2021-01-15 12:59 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️  🛑 

Hello again, Nice work working on the previous error 👍🏿  Your project looks amazing. Just a few more changes and your project will be good to go. Kindly check below ⬇️ 

- [ ] There should be a default project. At the moment, when a person views your application for the first time, there is a notice telling us that we don't have any project. However, this should not be the case. Kindly create a default project 😄 

### [OPTIONAL]

- [ ]  In your package.json, kindly add some more common commands like:  ` "start": "webpack-dev-server --mode development --open" `


### If you have any question kindly reach me on slack @peterrobert 

### HAPPY CODING 💻

2021-01-15 17:27 UTC, addod19 approved these changes
## Approved :trophy: :balloon:

Hi @rahalrazika and @lirad, congratulations on an amazing job done :+1: Having fix all the comments made by the previous TSE's and having met all the minimum requirements :slightly_smiling_face: I hereby approve the project :100: 

Go ahead and merge into the development :+1: 
Do not forget to submit the project completion form
_Happy coding_ :woman_technologist: :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-01-15 17:47 UTC, merged